evolution7_bugsnag_test_exception:
    pattern:  /exception
    defaults: { _controller: Evolution7BugsnagBundle:Default:exception }

evolution7_bugsnag_test_error:
    pattern: /error
    defaults: { _controller: Evolution7BugsnagBundle:Default:error }