evolution7_bugsnag_test_exception:
    path:  /exception
    defaults: { _controller: BugsnagBundle:Default:exception }

evolution7_bugsnag_test_error:
    path: /error
    defaults: { _controller: BugsnagBundle:Default:error }