parameters:
    bugsnag.api_key:
    bugsnag.notify_stages: [development, staging, production]
    bugsnag.client.class: Evolution7\BugsnagBundle\Bugsnag\Client
    bugsnag.exception_listener.class: Evolution7\BugsnagBundle\EventListener\ExceptionListener
    bugsnag.shutdown_listener.class: Evolution7\BugsnagBundle\EventListener\ShutdownListener
    bugsnag.release_stage.class: Evolution7\CoreBundle\System\ReleaseStage

services:
    bugsnag.client:
        class: %bugsnag.client.class%
        arguments: [%bugsnag.api_key%, @evolution7_core.release_stage, @service_container]

    bugsnag.exception_listener:
        class: %bugsnag.exception_listener.class%
        arguments: [@bugsnag.client]
        tags:
                    - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    bugsnag.shutdown_listener:
        class: %bugsnag.shutdown_listener.class%
        arguments: [@bugsnag.client]
        tags:
                    - { name: kernel.event_listener, event: kernel.controller, method: register }
