parameters:
    bugsnag.api_key:
    bugsnag.notify_stages: [staging, production]
    bugsnag.report_in_dev: false
    bugsnag.client.class: Evolution7\BugsnagBundle\Bugsnag\ClientLoader
    bugsnag.exception_listener.class: Evolution7\BugsnagBundle\EventListener\ExceptionListener
    bugsnag.shutdown_listener.class: Evolution7\BugsnagBundle\EventListener\ShutdownListener
    bugsnag.release_stage.class: Evolution7\BugsnagBundle\ReleaseStage\ReleaseStage

services:
    bugsnag.release_stage:
        class: %bugsnag.release_stage.class%

    bugsnag.client:
        class: Bugsnag_Client
        arguments: [%bugsnag.api_key%]

    bugsnag.clientloader:
        class: %bugsnag.client.class%
        arguments: [@bugsnag.client, @bugsnag.release_stage, @service_container]

    bugsnag.exception_listener:
        class: %bugsnag.exception_listener.class%
        arguments: [@bugsnag.clientloader]
        tags:
                    - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    bugsnag.shutdown_listener:
        class: %bugsnag.shutdown_listener.class%
        arguments: [@bugsnag.clientloader]
        tags:
                    - { name: kernel.event_listener, event: kernel.controller, method: register }
